[package]
name = "prickly"
version = "0.1.0"
authors = ["BenHall-7 <Benjaminjahall@gmail.com>"]
edition = "2018"

[dependencies]
tui-components = "0.1"
prc-rs = "1.4"
regex = "1.4"
structopt = "0.3"
itertools = "0.10"
num = "0.4"
